### ISSUE TITLE
AWS Django secret not set

### ISSUE THREAD

**Issue by michaelluich** [tomwillfixit/awx-on-swarm#1]
It looks like the "SECRET_KEY" is not getting set.
`

awx_awx.1.fio7qnmoqlb1@docker-210    | Traceback (most recent call last):
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/usr/bin/awx-manage", line 11, in <module>
awx_awx.1.fio7qnmoqlb1@docker-210    |     load_entry_point('awx==4.0.0.0', 'console_scripts', 'awx-manage')()
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 124, in manage
awx_awx.1.fio7qnmoqlb1@docker-210    |     prepare_env()
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/__init__.py", line 89, in prepare_env
awx_awx.1.fio7qnmoqlb1@docker-210    |     if not settings.DEBUG: # pragma: no cover
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
awx_awx.1.fio7qnmoqlb1@docker-210    |     self._setup(name)
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
awx_awx.1.fio7qnmoqlb1@docker-210    |     self._wrapped = Settings(settings_module)
awx_awx.1.fio7qnmoqlb1@docker-210    |   File "/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/conf/__init__.py", line 129, in __init__
awx_awx.1.fio7qnmoqlb1@docker-210    |     raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
awx_awx.1.fio7qnmoqlb1@docker-210    | django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
awx_awx.1.fio7qnmoqlb1@docker-210    | 2019-04-26 20:14:07,004 INFO success: callback-receiver entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`

**Comment by theneedyguy** [comment]
Getting the same issue

**Comment by joagonzalez** [comment]
same here
